module.exports = {
  COMMUNITY_CHAT: "COMMUNITY_CHAT",
  USER_CONNECTED: "USER_CONNECTED",
  MESSAGE_RECIEVED: "MESSAGE_RECIEVED",
  MESSAGE_SENT: "MESSAGE_SENT",
  USER_DISCONNECTED: "USER_DISCONNECTED",
  TYPING: "TYPING",
  VERIFY_USER: "VERIFY_USER",
  LOGOUT: "LOGOUT",
  PLAY_STATE: "PLAY_STATE",
  PLAY_STATE_CHANGED: "PLAY_STATE_CHANGED",
  VIDEO_ID: "VIDEO_ID"
};
